### PR TITLE
Use projectPath when reading files from disk

### LINKED ISSUE #255: `nin run` does not work from subfolders of a nin project
backend/watch.js does not use projectPath, so `nin run` crashes if the working directory is not the project root.

### PR DESCRIPTION
**Pull request by stianjensen**
This fixes #255.

### CODE REVIEW

File: nin/backend/serve.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ var serve = function(projectPath, shouldRunHeadlessly) {
       var path = data.path,
           filename = p.basename(path),
           filenameWithoutExtension = filename.split('.')[0],
-          content = fs.readFileSync(path, 'utf-8');
+          content = fs.readFileSync(projectPath + '/' + path, 'utf-8');
```
Comment (sigvef) [inline nin/backend/serve.js]: Consider using path.join.

**Comment by stianjensen** [comment]
ping
